### ISSUE TITLE
make_sites_monthly not working on GHA.

### ISSUE THREAD

**Issue by eqmh** [marinebon/p2p#27]
Hey @bbest, @7yl4r,
I added two new sites in Canada to [`data/sites.csv`](https://github.com/marinebon/p2p/blob/master/data/sites.csv). GHA ran successfully for [![make_pages_on_push](https://github.com/marinebon/p2p/workflows/make_pages_on_push/badge.svg)](https://github.com/marinebon/p2p/actions?query=workflow%3Amake_pages_on_push) and [make_obis_monthly](https://github.com/marinebon/p2p/blob/master/.github/workflows/make_obis_monthly.yml), but not for [make_sites_monthly](https://github.com/marinebon/p2p/blob/master/.github/workflows/make_sites_monthly.yml), which generated this error:

[install of package 'units' failed [error code 1]](https://github.com/marinebon/p2p/actions/runs/1171258026).

[make_sites_monthly](https://github.com/marinebon/p2p/blob/master/.github/workflows/make_sites_monthly.yml) has been failing for the past three months and satellite data on site pages are not up to date:

- SST: March-April 2021.
- Chl: May 2021
- Seascapes: January 2021. 

Thanks for looking at this!

**Comment by bbest** [comment]
Goal: update `renv.lock` with CRAN binary versions to prevent compilation errors with Github Action scripts and speed up running of scripts.

## install same version of R as in Github Actions

R 4.1.1

## source `shelf()`/`library()` calls in `scripts/`

Source `shelf()`, `library()` lines from `scripts/`:

- `functions.R`
- `make_pages.R`
- `make_sites.R`
- `obis_download.R`

### update to more recent versions, but binary only 

```
These packages have more recent versions available.
It is recommended to update all of them.
Which would you like to update?

1: All                                
2: CRAN packages only                 
3: None                               
4: htmltools (0.5.1.1 -> 0.5.2) [CRAN]
5: tibble    (3.1.3   -> 3.1.4) [CRAN]
6: stringi   (1.7.3   -> 1.7.4) [CRAN]

Enter one or more numbers, or an empty line to skip updates: 2
```

- Enter one or more numbers, or an empty line to skip updates:
  - **2**



```
  There are binary versions available but the source
  versions are later:
           binary source needs_compilation
htmltools 0.5.1.1  0.5.2              TRUE
tibble      3.1.3  3.1.4              TRUE
stringi     1.7.3  1.7.4              TRUE

Do you want to install from sources the packages which need compilation? (Yes/no/cancel) no
```

- Do you want to install from sources the packages which need compilation? (Yes/no/cancel)
  - **no**

```
> devtools::session_info()
─ Session info ──────────────────────────────────────────────────────────────────────────────────────
 setting  value
 version  R version 4.1.1 (2021-08-10)
 os       macOS Big Sur 11.4
 system   x86_64, darwin17.0
 ui       RStudio
 language (EN)
 collate  en_US.UTF-8
 ctype    en_US.UTF-8
 tz       America/Los_Angeles
 date     2021-08-27

─ Packages ──────────────────────────────────────────────────────────────────────────────────────────
 package      * version date       lib source
 assertthat     0.2.1   2019-03-21 [1] CRAN (R 4.1.0)
 backports      1.2.1   2020-12-09 [1] CRAN (R 4.1.0)
 base64enc      0.1-3   2015-07-28 [1] CRAN (R 4.1.0)
 bitops         1.0-7   2021-04-24 [1] CRAN (R 4.1.0)
 broom          0.7.9   2021-07-27 [1] CRAN (R 4.1.0)
 bsplus       * 0.1.2   2020-06-25 [1] CRAN (R 4.1.0)
 cachem         1.0.6   2021-08-19 [1] CRAN (R 4.1.0)
 callr          3.7.0   2021-04-20 [1] CRAN (R 4.1.0)
 caTools      * 1.18.2  2021-03-28 [1] CRAN (R 4.1.0)
 cellranger     1.1.0   2016-07-27 [1] CRAN (R 4.1.0)
 class          7.3-19  2021-05-03 [1] CRAN (R 4.1.1)
 classInt       0.4-3   2020-04-07 [1] CRAN (R 4.1.0)
 cli            3.0.1   2021-07-17 [1] CRAN (R 4.1.0)
 codetools      0.2-18  2020-11-04 [1] CRAN (R 4.1.1)
 colorspace     2.0-2   2021-06-24 [1] CRAN (R 4.1.0)
 crayon         1.4.1   2021-02-08 [1] CRAN (R 4.1.0)
 crosstalk      1.1.1   2021-01-12 [1] CRAN (R 4.1.0)
 crul           1.1.0   2021-02-15 [1] CRAN (R 4.1.0)
 curl           4.3.2   2021-06-23 [1] CRAN (R 4.1.0)
 data.table     1.14.0  2021-02-21 [1] CRAN (R 4.1.0)
 DBI            1.1.1   2021-01-15 [1] CRAN (R 4.1.0)
 dbplyr         2.1.1   2021-04-06 [1] CRAN (R 4.1.0)
 desc           1.3.0   2021-03-05 [1] CRAN (R 4.1.0)
 devtools       2.4.2   2021-06-07 [1] CRAN (R 4.1.0)
 digest         0.6.27  2020-10-24 [1] CRAN (R 4.1.0)
 dplyr        * 1.0.7   2021-06-18 [1] CRAN (R 4.1.0)
 dygraphs     * 1.1.1.6 2018-07-11 [1] CRAN (R 4.1.0)
 e1071          1.7-8   2021-07-28 [1] CRAN (R 4.1.0)
 ellipsis       0.3.2   2021-04-29 [1] CRAN (R 4.1.0)
 evaluate       0.14    2019-05-28 [1] CRAN (R 4.1.0)
 fansi          0.5.0   2021-05-25 [1] CRAN (R 4.1.0)
 fastmap        1.1.0   2021-01-25 [1] CRAN (R 4.1.0)
 forcats      * 0.5.1   2021-01-27 [1] CRAN (R 4.1.0)
 fs           * 1.5.0   2020-07-31 [1] CRAN (R 4.1.0)
 generics       0.1.0   2020-10-31 [1] CRAN (R 4.1.0)
 geojsonlint    0.4.0   2020-02-13 [1] CRAN (R 4.1.0)
 ggplot2      * 3.3.5   2021-06-25 [1] CRAN (R 4.1.0)
 glue         * 1.4.2   2020-08-27 [1] CRAN (R 4.1.0)
 gtable         0.3.0   2019-03-25 [1] CRAN (R 4.1.0)
 haven          2.4.3   2021-08-04 [1] CRAN (R 4.1.0)
 here         * 1.0.1   2020-12-13 [1] CRAN (R 4.1.0)
 hms            1.1.0   2021-05-17 [1] CRAN (R 4.1.0)
 hoardr         0.5.2   2018-12-02 [1] CRAN (R 4.1.0)
 htmltools      0.5.1.1 2021-01-22 [1] CRAN (R 4.1.0)
 htmlwidgets    1.5.3   2020-12-10 [1] CRAN (R 4.1.0)
 httpcode       0.3.0   2020-04-10 [1] CRAN (R 4.1.0)
 httpuv         1.6.2   2021-08-18 [1] CRAN (R 4.1.0)
 httr           1.4.2   2020-07-20 [1] CRAN (R 4.1.0)
 jsonlite       1.7.2   2020-12-09 [1] CRAN (R 4.1.0)
 jsonvalidate   1.1.0   2019-06-25 [1] CRAN (R 4.1.0)
 KernSmooth     2.23-20 2021-05-03 [1] CRAN (R 4.1.1)
 knitr        * 1.33    2021-04-24 [1] CRAN (R 4.1.0)
 later          1.3.0   2021-08-18 [1] CRAN (R 4.1.0)
 lattice        0.20-44 2021-05-02 [1] CRAN (R 4.1.1)
 lazyeval       0.2.2   2019-03-15 [1] CRAN (R 4.1.0)
 leafem       * 0.1.6   2021-05-24 [1] CRAN (R 4.1.0)
 leaflet      * 2.0.4.1 2021-01-07 [1] CRAN (R 4.1.0)
 librarian    * 1.8.1   2021-07-12 [1] CRAN (R 4.1.0)
 lifecycle      1.0.0   2021-02-15 [1] CRAN (R 4.1.0)
 lubridate    * 1.7.10  2021-02-26 [1] CRAN (R 4.1.0)
 magrittr       2.0.1   2020-11-17 [1] CRAN (R 4.1.0)
 mapedit        0.6.0   2020-02-02 [1] CRAN (R 4.1.0)
 mapview      * 2.10.0  2021-06-05 [1] CRAN (R 4.1.0)
 memoise        2.0.0   2021-01-26 [1] CRAN (R 4.1.0)
 mime           0.11    2021-06-23 [1] CRAN (R 4.1.0)
 modelr         0.1.8   2020-05-19 [1] CRAN (R 4.1.0)
 munsell        0.5.0   2018-06-12 [1] CRAN (R 4.1.0)
 ncdf4          1.17    2019-10-23 [1] CRAN (R 4.1.0)
 pillar         1.6.2   2021-07-29 [1] CRAN (R 4.1.0)
 pkgbuild       1.2.0   2020-12-15 [1] CRAN (R 4.1.0)
 pkgconfig      2.0.3   2019-09-22 [1] CRAN (R 4.1.0)
 pkgload        1.2.1   2021-04-06 [1] CRAN (R 4.1.0)
 plotly         4.9.4.1 2021-06-18 [1] CRAN (R 4.1.0)
 png            0.1-7   2013-12-03 [1] CRAN (R 4.1.0)
 prettyunits    1.1.1   2020-01-24 [1] CRAN (R 4.1.0)
 processx       3.5.2   2021-04-30 [1] CRAN (R 4.1.0)
 promises       1.2.0.1 2021-02-11 [1] CRAN (R 4.1.0)
 proxy          0.4-26  2021-06-07 [1] CRAN (R 4.1.0)
 ps             1.6.0   2021-02-28 [1] CRAN (R 4.1.0)
 purrr        * 0.3.4   2020-04-17 [1] CRAN (R 4.1.0)
 R6             2.5.1   2021-08-19 [1] CRAN (R 4.1.0)
 rappdirs       0.3.3   2021-01-31 [1] CRAN (R 4.1.0)
 raster       * 3.4-13  2021-06-18 [1] CRAN (R 4.1.0)
 Rcpp           1.0.7   2021-07-07 [1] CRAN (R 4.1.0)
 readr        * 2.0.1   2021-08-10 [1] CRAN (R 4.1.0)
 readxl         1.3.1   2019-03-13 [1] CRAN (R 4.1.0)
 remotes        2.4.0   2021-06-02 [1] CRAN (R 4.1.0)
 reprex         2.0.1   2021-08-05 [1] CRAN (R 4.1.0)
 rerddap      * 0.7.6   2021-08-18 [1] CRAN (R 4.1.0)
 rlang          0.4.11  2021-04-30 [1] CRAN (R 4.1.0)
 rmapshaper   * 0.4.5   2021-05-26 [1] CRAN (R 4.1.0)
 rmarkdown    * 2.10    2021-08-06 [1] CRAN (R 4.1.0)
 robis        * 2.6.1   2021-08-27 [1] Github (iobis/robis@8c7ca34)
 rprojroot      2.0.2   2020-11-15 [1] CRAN (R 4.1.0)
 rstudioapi     0.13    2020-11-12 [1] CRAN (R 4.1.0)
 rvest          1.0.1   2021-07-26 [1] CRAN (R 4.1.0)
 satellite      1.0.2   2019-12-09 [1] CRAN (R 4.1.0)
 scales         1.1.1   2020-05-11 [1] CRAN (R 4.1.0)
 sessioninfo    1.1.1   2018-11-05 [1] CRAN (R 4.1.0)
 sf           * 1.0-2   2021-07-26 [1] CRAN (R 4.1.0)
 shiny          1.6.0   2021-01-25 [1] CRAN (R 4.1.0)
 sp           * 1.4-5   2021-01-10 [1] CRAN (R 4.1.0)
 stringi        1.7.3   2021-07-16 [1] CRAN (R 4.1.0)
 stringr      * 1.4.0   2019-02-10 [1] CRAN (R 4.1.0)
 testthat       3.0.4   2021-07-01 [1] CRAN (R 4.1.0)
 tibble       * 3.1.3   2021-07-23 [1] CRAN (R 4.1.0)
 tictoc       * 1.0.1   2021-04-19 [1] CRAN (R 4.1.0)
 tidyr        * 1.1.3   2021-03-03 [1] CRAN (R 4.1.0)
 tidyselect     1.1.1   2021-04-30 [1] CRAN (R 4.1.0)
 tidyverse    * 1.3.1   2021-04-15 [1] CRAN (R 4.1.0)
 tzdb           0.1.2   2021-07-20 [1] CRAN (R 4.1.0)
 units          0.7-2   2021-06-08 [1] CRAN (R 4.1.0)
 usethis        2.0.1   2021-02-10 [1] CRAN (R 4.1.0)
 utf8           1.2.2   2021-07-24 [1] CRAN (R 4.1.0)
 V8             3.4.2   2021-05-01 [1] CRAN (R 4.1.0)
 vctrs          0.3.8   2021-04-29 [1] CRAN (R 4.1.0)
 viridisLite    0.4.0   2021-04-13 [1] CRAN (R 4.1.0)
 webshot        0.5.2   2019-11-22 [1] CRAN (R 4.1.0)
 withr          2.4.2   2021-04-18 [1] CRAN (R 4.1.0)
 xfun           0.25    2021-08-06 [1] CRAN (R 4.1.0)
 xml2           1.3.2   2020-04-23 [1] CRAN (R 4.1.0)
 xtable         1.8-4   2019-04-21 [1] CRAN (R 4.1.0)
 xts          * 0.12.1  2020-09-09 [1] CRAN (R 4.1.0)
 yaml         * 2.2.1   2020-02-01 [1] CRAN (R 4.1.0)
 zoo          * 1.8-9   2021-03-09 [1] CRAN (R 4.1.0)
```

## run `renv::snapshot()`, skip activate

```r
renv::snapshot()
```

```
Would you like to activate this project before snapshot? [Y/n]: n
```

- Would you like to activate this project before snapshot? [Y/n]:
  - **n**

```
The following package(s) will be updated in the lockfile:

# CRAN ===============================
- BH              [1.75.0-0 -> *]
- BiocManager     [1.30.10 -> 1.30.16]
- KernSmooth      [2.23-18 -> 2.23-20]
- MASS            [7.3-53 -> 7.3-54]
- Matrix          [1.3-2 -> 1.3-4]
- R6              [2.5.0 -> 2.5.1]
- RCurl           [1.98-1.2 -> *]
- Rcpp            [1.0.6 -> 1.0.7]
- V8              [3.4.0 -> 3.4.2]
- bitops          [1.0-6 -> *]
- blob            [1.2.1 -> 1.2.2]
- brio            [1.1.1 -> *]
- broom           [0.7.4 -> 0.7.9]
- bslib           [0.2.4 -> 0.2.5.1]
- cachem          [1.0.3 -> 1.0.6]
- callr           [3.5.1 -> 3.7.0]
- class           [7.3-18 -> 7.3-19]
- cli             [2.3.0 -> 3.0.1]
- colorspace      [2.0-0 -> 2.0-2]
- cpp11           [0.2.6 -> 0.3.1]
- crul            [1.0.0 -> 1.1.0]
- curl            [4.3 -> 4.3.2]
- data.table      [1.13.6 -> 1.14.0]
- dbplyr          [2.1.0 -> 2.1.1]
- desc            [1.2.0 -> 1.3.0]
- diffobj         [0.3.3 -> *]
- dplyr           [1.0.4 -> 1.0.7]
- e1071           [1.7-4 -> 1.7-8]
- ellipsis        [0.3.1 -> 0.3.2]
- fansi           [0.4.2 -> 0.5.0]
- farver          [2.0.3 -> 2.1.0]
- formatR         [1.7 -> 1.11]
- gdtools         [0.2.3 -> *]
- ggplot2         [3.3.3 -> 3.3.5]
- haven           [2.3.1 -> 2.4.3]
- highr           [0.8 -> 0.9]
- hms             [1.0.0 -> 1.1.0]
- httpuv          [1.5.5 -> 1.6.2]
- isoband         [0.2.3 -> 0.2.5]
- jqr             [1.2.0 -> 1.2.1]
- jquerylib       [0.1.3 -> 0.1.4]
- knitr           [1.31 -> 1.33]
- later           [1.1.0.1 -> 1.3.0]
- lattice         [0.20-41 -> 0.20-44]
- leafem          [trafficonese/leafem -> 0.1.6]
- leafpop         [0.0.6 -> 0.1.0]
- librarian       [1.7.0 -> 1.8.1]
- lifecycle       [0.2.0 -> 1.0.0]
- lubridate       [1.7.9.2 -> 1.7.10]
- maptools        [1.0-2 -> 1.1-1]
- mapview         [2.9.0 -> 2.10.0]
- mgcv            [1.8-33 -> 1.8-36]
- mime            [0.10 -> 0.11]
- mregions        [0.1.6 -> *]
- openssl         [1.4.3 -> 1.4.4]
- pillar          [1.4.7 -> 1.6.2]
- pkgbuild        [1.2.0 -> *]
- pkgload         [1.1.0 -> 1.2.1]
- plotly          [4.9.3 -> 4.9.4.1]
- praise          [1.0.0 -> *]
- processx        [3.4.5 -> 3.5.2]
- promises        [1.1.1 -> 1.2.0.1]
- protolite       [2.1 -> 2.1.1]
- ps              [1.5.0 -> 1.6.0]
- raster          [3.4-5 -> 3.4-13]
- readr           [1.4.0 -> 2.0.1]
- remotes         [2.2.0 -> 2.4.0]
- renv            [0.12.5 -> 0.14.0]
- reprex          [1.0.0 -> 2.0.1]
- rerddap         [0.7.0 -> 0.7.6]
- reticulate      [1.18 -> *]
- rlang           [0.4.10 -> 0.4.11]
- rmarkdown       [rstudio/rmarkdown@HEAD -> 2.10]
- rnaturalearth   [0.1.0 -> *]
- rvest           [0.3.6 -> 1.0.1]
- sass            [0.3.1 -> 0.4.0]
- servr           [0.21 -> 0.23]
- sf              [0.9-7 -> 1.0-2]
- stringi         [1.5.3 -> 1.7.3]
- svglite         [1.2.3.2 -> 2.0.0]
- systemfonts     [1.0.0 -> 1.0.2]
- testthat        [3.0.2 -> *]
- tibble          [3.0.6 -> 3.1.3]
- tidyr           [1.1.2 -> 1.1.3]
- tidyselect      [1.1.0 -> 1.1.1]
- tidyverse       [1.3.0 -> 1.3.1]
- tinytex         [0.29 -> 0.33]
- units           [0.6-7 -> 0.7-2]
- utf8            [1.1.4 -> 1.2.2]
- vctrs           [0.3.6 -> 0.3.8]
- viridis         [0.5.1 -> 0.6.1]
- viridisLite     [0.3.0 -> 0.4.0]
- waldo           [0.2.4 -> *]
- wellknown       [0.7.2 -> *]
- withr           [2.4.1 -> 2.4.2]
- wk              [0.3.4 -> 0.5.0]
- xfun            [0.21 -> 0.25]
- xts             [joshuaulrich/xts@HEAD -> 0.12.1]
- zoo             [1.8-8 -> 1.8-9]
- bit             [* -> 4.0.4]
- bit64           [* -> 4.0.5]
- dtplyr          [* -> 1.1.0]
- gargle          [* -> 1.2.0]
- googledrive     [* -> 2.0.0]
- googlesheets4   [* -> 1.0.0]
- ids             [* -> 1.0.1]
- proxy           [* -> 0.4-26]
- s2              [* -> 1.0.6]
- tzdb            [* -> 0.1.2]
- vroom           [* -> 1.5.4]

# GitHub =============================
- robis           [2.3.9 -> iobis/robis@HEAD]

Do you want to proceed? [y/N]: y
```

- Do you want to proceed? [y/N]: 
  - **y**

**Comment by bbest** [comment]
## `renv::snapshot(type="explicit")` with pkg deps in DESCRIPTION

```r
renv::snapshot(type="explicit", prompt=F)
```

**Comment by bbest** [comment]
Ok, above works seems to have solved it, eg https://github.com/marinebon/p2p/actions/runs/1174755258.

Here's the recipe for future updates:

1. **Install R** the same version on Mac as that of Github Action.
2. In RStudio **Packages** pane, update to _**Latest**_, but do not install from source for newer version, stick with binary only. Check versions of R packages with:
    ```r
    devtools::session_info()`
    ```
3. Update **`DESCRIPTION`** file with any package dependencies from scripts (see step 2).
4. Run the following to update the **`renv.lock`** file:
    ```r
    renv::snapshot(type="explicit", prompt=F)
   ```
6. **Git push** updates and **Run workflow** under [Actions](https://github.com/marinebon/p2p/actions)

**Comment by eqmh** [comment]
Thanks @bbest!

make_sites_monthly and make_obis_monthly seemed to run fine but the pages for the new added sites are not showing up. The site markers in Canada do appear on the main map but when you click them there is no page.

Also, something is returning a message on the home page (index.Rmd) and the Events page:

![image](https://user-images.githubusercontent.com/20710865/131173529-bbbdbb45-3bde-4f99-83c9-95a00b77d180.png)

![image](https://user-images.githubusercontent.com/20710865/131173628-eb0caa94-c2ed-4625-95f0-b98c534e5337.png)

**Comment by bbest** [comment]
Hi @eqmh,

I think I fixed everything above, but please let me know if not.

Cheers, Ben

**Comment by eqmh** [comment]
Hey @bbest,

The message is not showing up on the Home but is still present in the Events page.

Also, the pages of the two new sites in Nova Scotia (Black Beach and Mispec Beach) are not rendering when you click on the markers. Nonetheless, the html files were created in [docs](https://github.com/marinebon/p2p/tree/master/docs), and the SST and CHL tables are in the [data](https://github.com/marinebon/p2p/tree/master/data) folder.

The [obis_data.csv](https://github.com/marinebon/p2p/blob/master/data/obis/obis_data.csv) is now several thousands records larger likely from adding these two new sites, so that seems ok.

Thanks!
Enrique

**Comment by eqmh** [comment]
Hi @bbest,

I just noticed that the maps with satellite data are not up to date and so ran the _make_sites_monthly_ and _make_pages_on_push_ GHA's but got the same error of the 'units' package not installing.  Not sure how to follow your instructions above from Aug 27. 

I also need to make some other minor updates to our site that will require _make_pages_on_push_. 

Many thanks, again.

**Comment by bbest** [comment]
Ok, copying the error message from GH Action build https://github.com/marinebon/p2p/runs/6231041968?check_suite_focus=true#step:6:1049...

```
Installing units [0.7-2] ...
	FAILED
Error installing package 'units':
Error: Error: install of package 'units' failed [error code 1]
=================================

* installing *source* package ‘units’ ...
** package ‘units’ successfully unpacked and MD5 sums checked
** using staged installation
configure: units: 0.7-2
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether clang++ -mmacosx-version-min=10.13 -std=gnu++14 accepts -g... yes
checking how to run the C++ preprocessor... clang++ -mmacosx-version-min=10.13 -std=gnu++14 -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... rm: conftest.dSYM: is a directory
rm: conftest.dSYM: is a directory
yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for stdbool.h that conforms to C99... no
checking for _Bool... no
checking for error_at_line... no
checking for gcc... clang -mmacosx-version-min=10.13
checking whether we are using the GNU C compiler... yes
checking whether clang -mmacosx-version-min=10.13 accepts -g... yes
checking for clang -mmacosx-version-min=10.13 option to accept ISO C89... none needed
checking for XML_ParserCreate in -lexpat... yes
checking udunits2.h usability... no
checking udunits2.h presence... no
checking for udunits2.h... no
checking udunits2/udunits2.h usability... no
checking udunits2/udunits2.h presence... no
checking for udunits2/udunits2.h... no
checking for ut_read_xml in -ludunits2... no
configure: error: in `/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/Rtmpaoh3qd/R.INSTALL3ef03795e321/units':
configure: error: 
--------------------------------------------------------------------------------
  Configuration failed because libudunits2.so was not found. Try installing:
    * deb: libudunits2-dev (Debian, Ubuntu, ...)
    * rpm: udunits2-devel (Fedora, EPEL, ...)
    * brew: udunits (OSX)
  If udunits2 is already installed in a non-standard location, use:
    --configure-args='--with-udunits2-lib=/usr/local/lib'
  if the library was not found, and/or:
    --configure-args='--with-udunits2-include=/usr/include/udunits2'
  if the header was not found, replacing paths with appropriate values.
  You can alternatively set UDUNITS2_INCLUDE and UDUNITS2_LIBS manually.
--------------------------------------------------------------------------------

See `config.log' for more details
ERROR: configuration failed for package ‘units’
* removing ‘/Users/runner/work/_temp/Library/.renv/1/units’
Traceback (most recent calls last):
12: renv::restore()
11: renv_restore_run_actions(project, diff, current, lockfile, rebuild)
10: renv_install_impl(records)
 9: renv_install_staged(records)
 8: renv_install_default(records)
 7: handler(package, renv_install_package(record))
 6: renv_install_package(record)
 5: withCallingHandlers(renv_install_package_impl(record), error = function(e) {
        vwritef("\tFAILED")
        writef(e$output)
    })
 4: renv_install_package_impl(record)
 3: r_cmd_install(package, path)
 2: r_exec_error(package, output, "install", status)
 1: stop(error)
Execution halted
Error: Process completed with exit code 1.
```

**Comment by bbest** [comment]
Trying recommended fix with this run of [make_pages_on_push · marinebon/p2p@48f9fec](https://github.com/marinebon/p2p/actions/runs/2259462569):

https://github.com/marinebon/p2p/blob/48f9fecf7267200be06fbf7d5d49bda120e16d6c/.github/workflows/make_pages_on_push.yml#L29-L31

**Comment by bbest** [comment]
Now getting new error in [make_pages_on_push · marinebon/p2p@48f9fec](https://github.com/marinebon/p2p/runs/6261644913?check_suite_focus=true#step:7:1077):

```
Installing rgeos [0.5-5] ...
	FAILED
Error installing package 'rgeos':
Error: Error: install of package 'rgeos' failed [error code 1]
=================================

* installing *source* package ‘rgeos’ ...
** package ‘rgeos’ successfully unpacked and MD5 sums checked
** using staged installation
configure: CC: clang -mmacosx-version-min=10.13
configure: CXX: clang++ -mmacosx-version-min=10.13 -std=gnu++14
configure: rgeos: 0.5-5
checking for /usr/bin/svnversion... no
configure: svn revision: 640
checking for geos-config... no
no
configure: error: geos-config not found or not executable.
ERROR: configuration failed for package ‘rgeos’
```

Per [configure: error: geos-config not found or not executable. ERROR: configuration failed for package ‘rgeos’ problem while installing sf package on MacOS · Issue #1797 · r-spatial/sf](https://github.com/r-spatial/sf/issues/1797), going to try:

```bash
brew install pkg-config 
brew install gdal
```

**Comment by bbest** [comment]
Trying again with [make_pages_on_push · marinebon/p2p@656b51f](https://github.com/marinebon/p2p/runs/6263966702?check_suite_focus=true)

**Comment by bbest** [comment]
Ugh, `3.10.2` > `3.2.0` so the checking is wrong 😠 :

* [make_pages_on_push · marinebon/p2p@656b51f](https://github.com/marinebon/p2p/runs/6263966702?check_suite_focus=true#step:7:1077)

```
Installing rgeos [0.5-5] ...
	FAILED
Error: Error: install of package 'rgeos' failed [error code 1]
Error installing package 'rgeos':
=================================

* installing *source* package ‘rgeos’ ...
** package ‘rgeos’ successfully unpacked and MD5 sums checked
** using staged installation
configure: CC: clang -mmacosx-version-min=10.13
configure: CXX: clang++ -mmacosx-version-min=10.13 -std=gnu++14
configure: rgeos: 0.5-5
checking for /usr/bin/svnversion... no
configure: svn revision: 640
checking for geos-config... /usr/local/bin/geos-config
checking geos-config usability... yes
configure: GEOS version: 3.10.2
checking geos version at least 3.2.0... no
configure: error: Upgrade GEOS to at least 3.2.0
ERROR: configuration failed for package ‘rgeos’
```

**Comment by bbest** [comment]
Next step is removing dependency on these aging, ailing packages `rgeos` (and `rgdal`), per:

* [18.1 Retiring `rgdal` and `rgeos` | Spatial Data Science](https://keen-swartz-3146c4.netlify.app/older.html#retire)
* [relevant commands, exported by `rgeos` - Migrating · r-spatial/sf Wiki](https://github.com/r-spatial/sf/wiki/Migrating#relevant-commands-exported-by-rgeos)
